### ISSUE TITLE
Implement table prefix support

### ISSUE THREAD

**Issue by Caravus** [nvlad/yii2support#110]
Seems like plugin cant find my tables. What information you need for debug?

**Comment by insperedia** [comment]
Do you use table prefix?

**Comment by Caravus** [comment]
Yes.
```
 public static function tableName()
    {
        return '{{%services}}';
    }
```

**Comment by insperedia** [comment]
They are not supported yet. I ll put in feature requests. Thanks.

**Comment by Caravus** [comment]
Any news?

**Comment by insperedia** [comment]
Unfortunatly for implementation of table prefixes plugin need to understand configuration files. Due to high dynamic nature of Yii's configs files its looks like tricky task. So right now this functionality is not on my roadmap. I belive there no problem to make a local db without prefix to make it work. Plugin understands {{% siyntax, but can not use prefix is it exists.

**Comment by insperedia** [comment]
In testing right now. Are you ready to help with testing?

**Comment by insperedia** [comment]
yii2support plugin with tablePrefix support is available  in Beta channel: https://plugins.jetbrains.com/plugin/download?updateId=39083
Feel free to make beta testing and post bugs in github.
